int SCREENX =400;
int SCREENY = 400;
int BULLETWIDTH=5;
int BULLETHEIGHT=15;
int MARGIN=10;
int GAP=5;
int PLAYER_HEIGHT = 37;
int PLAYER_WIDTH = 57;
int ALIEN_HEIGHT = 25;
int ALIEN_WIDTH = 30;

int BONUS_HEIGHT = 15;
int BONUS_WIDTH = 15;

int BOMB_RADIUS = 10;


int SHIELD_WIDTH = 50;
int SHIELD_HEIGHT = 20;